### ISSUE TITLE
Invert git submodule relationship with Mina repo

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#1096]
## Why

In terms of logical dependency, SnarkyJS depends on the Mina repo, but Mina (the node software and related utilities) doesn't depend on SnarkyJS.

However, the git relationship is reversed: SnarkyJS is a git submodule of the Mina repo.

A consequence of the reversed setup is that for each branch on the Mina repo, there also _has_ to be a corresponding SnarkyJS version, which successfully compiles together with that Mina code base and passes basic tests (this is enforced in CI). This is unintended -- here's no reason to keep SnarkyJS working with every possible incarnation of Mina.

If we inverted the submodule relationship, we could be intentional about which versions of SnarkyJS + Mina we want to maintain (e.g., one that's in sync with the current testnet, and one that tracks changes necessary for the upcoming testnet). This would reduce the burden for some developers that do a lot of SnarkyJS-impacting changes. Those changes could be brought to SnarkyJS as a separate step, possibly in batches, in a way that doesn't block landing the corresponding changes in the Mina repo. 

In short, it just makes sense if the logical dependency is reflected in the submodule structure.

## How

* Add a new git submodule to SnarkyJS, at `src/mina`
* Make dune compilation work in that new setup
* Remove the git submodule at `src/lib/snarkyjs` from the Mina repo. Land that change in a place where it is upstreamable to all major Mina dev branches, e.g. `rampup`.
* (see below) Develop a solution for tests in Mina CI

## Unresolved

There is one unresolved question: What do we do with the existing tests in Mina CI that check that SnarkyJS can be compiled from its OCaml and Rust sources, and works? These tests seem important. SnarkyJS CI is currently a cheap GH action setup and would need a lot of work to be able to compile from source in CI. Also, having those tests in Mina CI had the benefit ot immediately alerting people when changes broke SnarkyJS compilation -- the CI tests recently have been carefully refactored to only fail on basic build errors and e2e SnarkyJS crypto breakage (i.e. failing to generate a proof). The tests aren't blocking protocol changes that aren't reflected in SnarkyJS, which we agreed isn't suitable to keep in sync on a per-PR basis.

**Comment by shimkiv** [comment]
Since SnarkyJS will now have Mina as submodule then it makes sense to execute such a test in SnarkyJS CI. 
One simple way to do this is to follow similar approach as we did with the [Docker Images building procedure](https://github.com/o1-labs/mina-lightnet-docker/blob/develop/.github/workflows/build.yml).
This approach a). won't require loads of work to compile everything from sources, build system is already ready and consumed. and b). will let us stay with the same CI but offload all the heavyweight tasks to cloud VM(s).
Currently this is the Hetzner VM snapshot with ready to use mina build system, with everything configured to build mina from sources on all major branches (adding here snarkyjs build is a matter of slightly changing the scripts). Then GitHub Action job creates VM from the snapshot mentioned using Hetzner API and executes all the stuff. VM is turned off and deleted on Job completion.

**Comment by mitschabaude** [comment]
Thanks @shimkiv I like this suggestion! We should definitely build that into SnarkyJS CI.

I'm not 100% convinced we should remove _all_ checks in Mina CI that prevent SnarkyJS breakage. At the same time, we don't want Mina CI to depend on another repo (that would make fixes too awkward if the tests fail).

So what I'm proposing is the following:
- full e2e snarkyjs build and integration test in SnarkyJS, with the methods @shimkiv outlined
- replace snarkyjs in Mina with a stub OCaml module, let's call it `snarkyjs-stub`. It has the same dependencies as snarkyjs used to have, but only stub code, and in Mina CI we check that it can be dune-compiled. We also add a unit test, written in OCaml and run with JSOO, which checks that basic proof generation works in the JS target. This way, we achieve the following:
  - if the JS build breaks in an unintended way (as has happened often in the past, because certain popular OCaml libraries can't compiled to JS and they easily get added if nothing prevents that), Mina CI will catch that, ensuring we find a different solution
  - same if e2e proof generation breaks (would happen often without a test, because it would be easy to change the OCaml-Rust bindings without changing the JSOO-Wasm bindings in exactly the same way)
  - on the other hand, if snarkyjs-stubs tests break in an intended way, it can be fixed right in the Mina repo (without painful repo-switching and separate PRs), and at the later stage when those changes are brought to snarkyjs, we already see what in the snarkyjs dependencies has to be updated

**Comment by MartinMinkov** [comment]
I just wanted to reflect on some discussions we had internally with @shimkiv and @dkijania 

Action items:
1. Investigate removing `o1js` as a dependency for the Rosetta tests. Instead, manually construct AccountUpdates/zkApp transactions with protocol library code instead of having `o1js` do this to test Rosetta interaction.

2. Document and communicate branching strategy with Velocity relating to matching and compatible `o1js` and `mina` branches. Make sure we are aligned on how this is done.

3. Add the compile/proof tests in place of the `snarkyjs` submodule, to be done by Product Eng

**Comment by MartinMinkov** [comment]
Once o1js can be built with Mina as a submodule, we need to complete the following to make sure the o1js stub code will work as expected:
1. https://github.com/o1-labs/o1js-bindings/issues/200
2. https://github.com/MinaProtocol/mina/issues/14466
