### ISSUE TITLE
`getAndAssertEquals` -> `get` ?

### ISSUE THREAD

**Issue by L-as** [o1-labs/o1js#1129]
This is probably confusing for beginners,
especially when people do `x.assertEquals(x)`.

When would you use raw `get` over `fetch` anyway?

**Comment by bkase** [comment]
there are (rare) times where you want to get without asserting, but it seemed cleaner than requiring the two lines of code everytime.

**Comment by L-as** [comment]
Yes but that is the special-case, and it should be named as such. `get` should assert, the original one should be renamed, and it's not clear to me how it's different from `fetch`.

**Comment by mitschabaude** [comment]
I disagree, because adding a precondition is something that can have negative impact on UX, by introducing race conditions. Something like that shouldn't happen silently. That's why I prefer the more explicit `getAndAssertEquals()`

Re difference:
* `fetch()` is async and therefore can't be used in a smart contract method
* `get()` is sync, and has two modes: one where it returns a dummy value and marks the account to be fetched, and one where it returns something from cache. By running the contract method twice and doing the fetch in between, we enable a synchronous API. This aspect of `get()` is really just a hack around not having async circuits (currently)
* `get()` puts the result in a witness. using the `fetch()` result directly would mean you use a different constant every time you compile/prove the circuit, so it'd be broken

**Comment by L-as** [comment]
I understand your viewpoint but it's highly likely that at least one person will mistakenly use `.get()` instead of `.getAndAssertEquals()` which would be a fatal security bug AFAIU.

**Comment by mitschabaude** [comment]
> I understand your viewpoint but it's highly likely that at least one person will mistakenly use `.get()` instead of `.getAndAssertEquals()` which would be a fatal security bug AFAIU.

But o1js throws an exception in that case!
