### ISSUE TITLE
Set up CI to ensure CLI examples & project template version match SnarkyJS version being published

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/o1js#139]
To prevent examples from falling out of date.

**Comment by mitschabaude** [comment]
One idea to solve this would be: The examples live in snarkyjs and are tested in CI, and the CLI just copies them over from the snarkyjs version it has installed in node_modules. Not sure how brittle it is to explicitly rely on node_modules, maybe there's a better way. But this would also simplify iterating on these examples, which is currently super annoying, since in the CLI template directories, there is no linting and no simple way to just run something

**Comment by mitschabaude** [comment]
Or maybe the cli should become a git submodule of snarkjys? Or of mina?

**Comment by Trivo25** [comment]
Not an issue anymore AFAIK
