### ISSUE TITLE
Fetch `networkId` automatically from GraphQL endpoint

### ISSUE THREAD

**Issue by L-as** [o1-labs/o1js#1492]
That way when using custom networks you don't have to set the salt for both account update hashing and signatures manually.

**Comment by L-as** [comment]
https://github.com/MinaProtocol/mina/blob/f16675abd2cee3c39a10f450bdc6fa3f6c998404/graphql_schema.json#L15319 for reference

**Comment by Trivo25** [comment]
Right now, you will have to specify a custom network like this

```ts
Mina.Network({
    // ...
    networkId: 'mainnet',
});

// mina-signer
let client = new Client({ network: 'mainnet' });
```

Which the developer will have to do once they publish their zkApp on a website or somewhere else. Do you think fetching would still be better? I like the explicit declaration of the network, especially since it's a tiny change - it clearly marks what network you want to interact with (default being the testnet)

**Comment by L-as** [comment]
Even if it's made explicit, at the very least it should automatically be checked against what the endpoint returns. FWIW `signatureKind` might be the correct thing to fetch, since multiple networks might use same signatures, OTOH, that should optimally never be the case.

**Comment by L-as** [comment]
@Trivo25 what fixed this?
