### ISSUE TITLE
implicitly prove txs

### ISSUE THREAD

**Issue by harrysolovay** [o1-labs/o1js#1547]
Are there use cases in which the creation of a transaction, targeting a non-test chain, is **not** to be `prove`n? If so, the need to explicitly call `prove` makes sense. Otherwise, perhaps the `prove` method can happen implicitly in the initial `transaction` creation call?

Some additional thoughts:

## Backward Compatibility

This could be implemented such that any subsequent `prove` calls return the initial (cached) result. Would this preserve backward compatibility?

```ts
const unsent = Mina.transaction(sender, async () => {
  // `prove` is implicitly called
})
// the following `prove` call is a noop
await unsent.prove()
```

## Top-level Prove Toggle

Meanwhile, the proving could be disabled by the top-level `proofsEnabled` field in the case of the in-mem test chain.

```ts
let Local = Mina.LocalBlockchain({ proofsEnabled: false })
Mina.setActiveInstance(Local)

const unsent = Mina.transaction(sender, async () => {
  // `prove` is NOT called
})
```

## Pending Proof Access

One could access the pending proof state on the pending transaction creation.

```ts
const unsent = Mina.transaction(sender, async () => {
  // ...
}) // `CreateTransactionPromise`

const proof = await unsent.proofPromise // Promise<(Proof<ZkappPublicInput, undefined> | undefined)[]>
```

**Comment by mitschabaude** [comment]
I think I'm ultimately opposed to this proposal.
Some objections:
* Proving is a very slow and clunky operation. I feel like operations like that should generally be triggered explicitly.
* When I debug my transactions, including errors when proving them, I usually log the transaction after it was constructed, but before proving, so that I can double-check that it's valid. This would no longer be possible when proving happened inside `transaction()`
* It's not always the ideal architecture to prove transactions right in the process where they are created by a user. In the future, we want to enable outsourcing the proving to a server / cloud service. It therefore feels premature to entangle the proving step with the step of calling the contract / computing the proof inputs.

**Comment by harrysolovay** [comment]
Makes sense complete sense.
