### ISSUE TITLE
o1js does not work with next server

### ISSUE THREAD

**Issue by 45930** [o1-labs/o1js#1811]
## Summary

o1js cannot be used on a server with the next.js platform.  DFST noted the issue in [this discord thread](https://discord.com/channels/484437221055922177/1233356603424641025/1244565500218966040) but I don't believe we've addressed the issue since.

The issue: `Error: ENOENT: no such file or directory, open '.../.../.next/server/vendor-chunks/plonk_wasm_bg.wasm'` seems to be caused by the way next builds its dependencies.  A similar discussion is opened here: https://github.com/vercel/next.js/discussions/56634

**Comment by mitschabaude** [comment]
next doesn't find the wasm file at its location because it bundles the o1js code and o1js depends on the wasm file's relative location implicitly.

it seems hard to make next infer that it should also bundle the wasm file.

so, my approach would be: make next not bundle the o1js code at all, instead load it directly from `node_modules`. should be no problem in principle to skip bundling since it all runs in node! (for web, o1js provides a single-file bundle that bundlers should be able to merge into their bundle)

**Comment by 45930** [comment]
Yep that checks out!  I wasn't able to find the one-liner config option to do this at a glance, but that approach makes sense in theory.

**Comment by anarkrypto** [comment]
@45930 I was able to fix with this config:

```js
module.exports = {
  webpack: (config, { isServer }) => {
    if (isServer) {
      config.externals.push('o1js');
    }
    return config;
  },
};
```

**Comment by 45930** [comment]
@anarkrypto amazing, thank you for the config!  I will add this to the zkapp-cli default

**Comment by 45930** [comment]
https://github.com/o1-labs/zkapp-cli/pull/693
