### ISSUE TITLE
Put MerkleWitness on MerkleTree so that height is baked in

### ISSUE THREAD

**Issue by bkase** [o1-labs/o1js#574]
```
const tree = new Experimental.MerkleTree(height);
class MerkleWitness extends Experimental.MerkleWitness(height) {}
```

It's a bit awkward to have to extend a class for each different type of MerkleTree height -- also we only catch height mis-match errors at runtime.

Instead could we make `MerkleTree` and `MerkleWitness` have a compile-time generic argument for the height (which in all use-cases I can come up with in 30 seconds of thinking about it, we'll always know at compile time) for better safety and less awkward needs for eg making a `MerkleWitness20` and a `MerkleWitness32` etc ala https://github.com/o1-labs/docs2/pull/101/files

**Comment by mitschabaude** [comment]
The reason we extend classes in APIs like this is that a class is, to my knowledge, the only way to create a type which is simultaneously recognized as a _value_ by decorators.

The method decorator does some magic where you only specify the method arguments as _types_:
```ts
@method myMethod(arg: MerkleWitness20) {
```
...and then we're able to get a corresponding JS value, which is the class `MerkleWitness20`. We need this so that in the circuit wrapper code, we can convert the method arguments to witnesses. So in principle our code will do this:
```ts
let modifiedArg = Circuit.witness(MerkleWitness20, () => arg);
```
In the code above, it's important that the number 20 is baked in because it determines the Merkle witnesses' size in field elements.

So the gist is: For each different representation as field elements, we need a different class.

There's no way to reuse one generic class for different types which differ in their representation as field elements, because the decorator doesn't give us metadata about the generic type argument.

**Comment by mitschabaude** [comment]
In a non-class API without decorators, we wouldn't need to create a type with a special name, but we would still need to create a special value. So for example, the following syntax would work  for ZkProgram:

```ts
// ...
methods: {
  myMethod: {
    privateInputs: [MerkleWitness(20)] // no class extending, just call a function to create your value
    
    method(arg: MerkleWitness) { // type could be just on type or also have a generic argument
    }
  }
}
```

**Comment by bkase** [comment]
Maybe consider embedding `MerkleWitness` under the `MerkleTree` -- `MerkleTree.MerkleWitness` so they share the same height?
