### ISSUE TITLE
All fetch errors are interpreted as "Could not find account"

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#657]
TODO: Better discriminate between different kinds of errors in places like `Mina.getAccount`. Example:
* If the endpoint doesn't respond, that should always result in an error
* A missing, on the other hand, account is sometimes an error (e.g. in `getAccount`) and sometimes just information that this account doesn't exist yet (in `hasAccount`)

**Comment by Pfed-prog** [comment]
Really great to find an existing issue for the `Error: getAccount:`

Currently I am using this script to catch the error when the balance is zero.


```ts
import { PublicKey, Mina } from 'o1js';

import { MerkleMapContract } from '../NFTsMapContract.js';

export function logTokenBalances(
  address: PublicKey,
  dexApp: MerkleMapContract
) {
  let balance = 0n;
  try {
    balance = Mina.getBalance(address, dexApp.token.id).value.toBigInt();
  } catch (e) {
    console.log(e);
  }

  console.log(address.toBase58() + ' zkApp tokens:', balance);
}
```

`Mina.getAccount(address, dexApp.token.id).balance.toString();`

![image](https://github.com/o1-labs/o1js/assets/66903336/da99a137-c0ef-48e3-ad03-627111941300)

instead of `getBalance` produces the same error

![image](https://github.com/o1-labs/o1js/assets/66903336/40b81f2a-033b-4c87-b5dd-d15566cf6ed9)
