### ISSUE TITLE
sha256 hash

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/o1js#731]
Why? It's an very common hashing function in other ecosystems, which makes it useful for many architectural designs. For example, many bridge designs require a common hashing function on each side.

docs happening in https://github.com/o1-labs/docs2/pull/795

**Comment by mitschabaude** [comment]
@garwalsh This is now easy to do by using existing custom gates, and is still something that people regularly ask for. I also consider this an opportunity to showcase the power of our new gates (bitwise AND, XOR, NOT etc) directly within snarkyjs, for the first time

**Comment by Trivo25** [comment]
to whoever picks this up:
- ROT32 needs to be implemented, current rotation only works over 64 bit sized blocks
- addition mod 2n**32n also needs to be implemented

**Comment by mitschabaude** [comment]
> to whoever picks this up

More pointers:
* rot32 is doable with a double generic gate plus one extra 32-bit range check (the rot64 inlines a 64-bit range check)
* 32-bit range checks are `UInt32.check(x)`. They take 2 rows instead of 1 row like `rangeCheck64`, so performance of sha2 will suffer somewhat compared to keccak
* addition mod 32 bits is just `a + b === q*2^32 + r`, where the outputs q and r have to be 32-bit range checks

**Comment by MartinMinkov** [comment]
I'd like to take this on if nobody else has issues with that!
