### ISSUE TITLE
Eslint doesn’t have global context as it’s currently configured

### ISSUE THREAD

**Issue by bkase** [o1-labs/o1js#769]
If a ZK contract calls another in another file eslint misses it.

**Comment by mitschabaude** [comment]
Not sure I understand what the linter misses! Why shouldn't a zkApp contract call another in another file?

I think, as currently configured, eslint doesn't process TS files at all. We rely on `ts` (built into VS code) as the linter, which enforces correctness of syntax & types. It _is_ true that TS sometimes misses if things aren't declared & used in the right order, so something is actually undefined because it is used before declared
