### ISSUE TITLE
fetchEvents returns events in different order than local blockchain

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#859]
Reported by @mitschabaude 

@MartinMinkov I assume this is just because we don't do `fetchedEvents.reverse()` inside `fetchEvents()`, as we do for actions?

**Comment by MartinMinkov** [comment]
Yup, a `.reverse()` inside `fetchEvents()` would fix this! Although, I would question whether fetching events in the order they happened is the most common use case. Is there a case for changing LocalBlockchain to return the latest events instead? I can image use cases like a UI listening for events; you would probably be most interested in the latest events dispatched rather than fetching events and looking at the end for the ones you want. WDYT?

**Comment by mitschabaude** [comment]
Good point @MartinMinkov!
