### ISSUE TITLE
Cannot read properties of undefined (reading 'memory') in plonk wasm file

### ISSUE THREAD

**Issue by 45930** [o1-labs/o1js#995]
When I run `vite build` in my app, I get this error:

```
vite v4.3.9 building SSR bundle for production...
✓ 68 modules transformed.

node:internal/event_target:916
  process.nextTick(() => { throw err; });
                           ^
TypeError [Error]: Cannot read properties of undefined (reading 'memory')
    at Object.<anonymous> (/Users/me/Projects/zkapps/mina-rng/node_modules/snarkyjs/dist/node/_node_bindings/plonk_wasm.cjs:14:27)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.wrappedLoad [as _load] (/Users/me/Projects/zkapps/mina-rng/node_modules/newrelic/lib/shimmer.js:313:24)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
```

I am using version `0.10.1`.

**Comment by mitschabaude** [comment]
It seems that vite tries to bundle the nodejs version of snarkyjs instead of using the prebuilt web bundle - this won't work for a couple of reasons

**Comment by mitschabaude** [comment]
SnarkyJS tries to tell bundlers how to resolve the import by declaring an 'exports' field in package.json. I would assume that vite can handle that, but maybe we have to tweak for it to work

**Comment by mitschabaude** [comment]
Oh.. just realized that it refers to the 'SSR bundle'. So it bundling the node version is correct after all (although I don't see the point of bundling code for nodejs, after all it works to just execute it)

**Comment by 45930** [comment]
@mitschabaude In the past I've had success by just disabling SSR for all of my pages.  I can try that.

This is the RNG app I built for zk-ignite cohort 0, which was working fine before.  I found that if I update just the snarkyJS version and pin `@svekte/kit` and `@svelte/adapter-node` to their previous versions, then the app builds.  But in the zkapp-cli, you are using the newest version of `@svelte/kit` and `@svelte/adapter-auto` in the example project, which builds fine.  It's annoying to have to track down build errors more often than not when making new projects and updating old ones.


> just realized that it refers to the 'SSR bundle'. So it bundling the node version is correct after all 

Is this actually true?  My understanding of SSR is that the server generates an html and js functions before the user requests it, but then if the user interacts with those functions, then they will be executed in a browser environment, not in node.  That's why it's always made sense to me to _disable_ SSR for snarkyJS interactions.

**Comment by mitschabaude** [comment]
Hm maybe we should pin the sveltekit version 🤔

**Comment by 45930** [comment]
@mitschabaude the mina-rng app does not use the zkapp-cli scaffolding.  I only mention that because that scaffold _does_ use the most up-to-date of every package, and my app only works when I _don't_.

I should clarify something - the mina-rng app only uses snarkyJS on the server side.  The html in the app is just some documentation about how to use the API.  The API is where I use snarkyJS to sign data, and node is the correct execution environment to use.

```
let { isMainThread, workerData } = require('worker_threads');

let env = {};
if (isMainThread) {
  env.memory = new WebAssembly.Memory({
    initial: 20,
    maximum: 65536,
    shared: true,
  });
} else {
  env.memory = workerData.memory;  <-------
}
```

This is the the line with the error.  `workerData` is apparently undefined (`Cannot read properties of undefined (reading 'memory')`), but it is required and should be present?  My node version is `v16.14.2`

**Comment by 45930** [comment]
For reference, here's the app: https://github.com/45930/mina-rng

**Comment by mitschabaude** [comment]
> I only mention that because that scaffold does use the most up-to-date of every package, and my app only works when I don't.

I understood that! Pinning would solve it randomly breaking when new versions come out

Yeah the error you have is weird. Maybe the code doesn't work because it all runs in a worker so isMainThread is never true?

**Comment by leomanza** [comment]
@mitschabaude @45930 have you found a fix for this error? we are facing the same issue running `vite build`
We are using:
 "snarkyjs": "^0.12.1",
 "@sveltejs/adapter-auto": "^2.0.1",
 "@sveltejs/kit": "^1.15.10",
"@sveltejs/adapter-static": "^2.0.2"

SSR is disabled

**Comment by ymekuria** [comment]
#@leomanza are you running into this error after generating a svelte project using the zkapp-cli?

**Comment by mazito** [comment]
Yes, we have used this: [https://github.com/mazito/zkLearn/tree/main/05-zkapp-sveltekit-ui](https://github.com/mazito/zkLearn/tree/main/05-zkapp-sveltekit-ui) that was based on the zkapp-cli, because the zkapp-cli had problems already described in this post.

Initially we had no problems with build, but from what I am testing now the problem seems to happens with dynamic routes (such as `/credentials/[uid]` and similar), because svelte-kit can not prerender them.

Please note the we are prerendering all pages.

**Comment by mazito** [comment]
So, this is what I have found so far.

**First we set prerender on all pages**, so `+layout.js` contains:
~~~
// for generating a static site
export const prerender = true;
export const ssr = false;
export const csr = true;

// may need it for static sites ??? NOT SURE
export const trailingSlash = 'always';
~~~

**Second, we add dynamic pages to the `prerender`** section in `svelte.config.js`:
~~~
//import adapter from '@sveltejs/adapter-auto';
import adapter from '@sveltejs/adapter-static';
import { vitePreprocess } from '@sveltejs/kit/vite';
import path from 'path';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  // Consult https://kit.svelte.dev/docs/integrations#preprocessors
  // for more information about preprocessors
  preprocess: vitePreprocess(),

  kit: {
    // adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
    // If your environment is not supported or you settled on a specific environment, switch out the adapter.
    // See https://kit.svelte.dev/docs/adapters for more information about adapters.
    adapter: adapter({
      // default options are shown. On some platforms
      // these options are set automatically — see below
      pages: 'build',
      assets: 'build',
      // fallback: undefined, // for static site
      fallback: 'index.html', // for SPA
      precompress: false,
      strict: true
    }),

    prerender: {
      entries: [
        '*',
        '/credential/claimed/[uid]',
        '/credential/issued/[uid]',
        '/credential/edit/[uid]',
      ]
    },

  }
};

export default config;
~~~

**Then it builds, except when we import something from `snarkyjs` in the `+pages.js` of the given page**. 

For example, the following code in `/credential/claimed/[uid]/+pages.js`:
~~~
import { error } from '@sveltejs/kit';
import { getPlan, getCommunity, getClaim } from "@apis/queries";
import { getCurrentUser } from '@models/current-user';


async function loadClaim(params, user) {
  const claimUid = params.uid;

  let claim = await getClaim(claimUid);

  const plan = await getPlan(claim.planUid);

  const org = await getCommunity(claim.communityUid);

  claim.community = org.name;
  claim.type = plan.name;
  claim.description = plan.description;
  claim.image = plan.image; 

  return claim; 
}


/** @type {import('./$types').PageLoad} */
export async function load({ params, route, url }) {
  if (params.slug !== "") {
      let user = await getCurrentUser();

      let aClaim = await loadClaim(params, user);
      return JSON.parse(JSON.stringify(aClaim));
    }
    throw error(404, 'Not found');
}
~~~

Builds correctly:
~~~
...
.svelte-kit/output/server/index.js                                                          83.51 kB

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static
  Wrote site to "build"
  ✔ done
✓ built in 7.36s
~~~

**BUT adding just `import { Field } from 'snarkyjs';` to the top of the same code it generates the error**:

~~~

node:internal/event_target:1036
  process.nextTick(() => { throw err; });
                           ^
TypeError [Error]: Cannot read properties of undefined (reading 'memory')
    at Object.<anonymous> (/home/mzito/tmp/sc-ui2/node_modules/snarkyjs/dist/node/bindings/compiled/_node_bindings/plonk_wasm.cjs:14:27)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:309:10)
    at [kOnMessage] (node:internal/worker:320:37)
    at MessagePort.<anonymous> (node:internal/worker:216:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:761:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v19.9.0
~~~

**Please note** that since we are using an static adapter and forcing CSR and disabling SSR for all pages (it is an SPA), it should never try to include any node code, as it seems it is happening.

Conclusions:

- Including `snarkyjs` in any `+page.js` generates the build error.
- Including snarkyjs (or some other code that includes snarkyjs) in `.svelte` files seems to work ok.

Hope this helps.

**Comment by ymekuria** [comment]
@mazito @45930 I believe we fixed this issue in the `zkapp-cli` scaffold after adding this to the vite config. 
```
   optimizeDeps: {
        esbuildOptions: {
            target: 'esnext'
        }
    },
```

You should be able to generate and build a Svelte project using the `zkapp-cli` with the latest version `0.11.0` although the scaffold does not use a static adapter.

**Comment by mazito** [comment]
@ymekuria Yes, I have that option already settled in the project. 

And it works fine for static routes, but **the problem reported here is different, it happens with dynamic routes** (such as `/credential/[uid]`).  I don't know if only with static adapter, but I suppose not.

Have you tested it with dynamic routes and including `snarkyjs` in the `+pages.js` of such routes ?

Anyway I solved it by:

1) cleaning up all snarkyjs imports from those pages, and also avoiding to import any code that imports snarky in any `+pages.js` too. 

2) including those dynamic routes in the `prerender.entries` section of `svelte.config.js`.

Just writing it here for anyone who may have the same problem.
